highcharts:
  jshead:
    - js/jquery-1.9.1.min.js
    - js/highstock.js
    - js/highcharts-more.js
    - js/exporting.js
  cdn:
    jshead:
      - "http://code.jquery.com/jquery-1.9.1.min.js"
      - "http://code.highcharts.com/stock/highstock.js"
      - "http://code.highcharts.com/highcharts-more.js"
      - "http://code.highcharts.com/stock/modules/exporting.js"
